### ISSUE TITLE
Tried fresh installation, ldap fails

### ISSUE THREAD

**Issue by hpanago** [hpanago/Django_Template_Blog#1]
Getting the error, ``` from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion
ImportError: No module named django_auth_ldap.config```

while having install django-auth-ldap with pip.

**Comment by arka-nitd** [comment]
@hpanago I would like to work on this issue. Please describe how to create the same. As of now I have installed the modules specified in readme but unable to start the server ? Is there any other requirements ?

**Comment by hpanago** [comment]
@arka-nitd  I will try to recreate it tomorrow and give you more details.

The only thing I can imagine begin different are the queries done to the ldap as I do not provide the ldap's schema. Will check this as well.

There should not be any more requirements. Could you provide me with the error that it gives you when you try to start the server? So I can help you more.

Thanks a lot for taking a look at my repo :)

**Comment by arka-nitd** [comment]
![image](https://user-images.githubusercontent.com/9302564/31197633-557e0d54-a96f-11e7-97ce-6771b9d4494c.png)
Something of this sort

**Comment by hpanago** [comment]
Maybe pip install django-adldap-sync could do the trick. 

I think I generally don't use synchronization of the ldap server anywhere, so we could take it off of settings.py entirely.

After installing ldap and not python-ldap mine still gets stuck at ImportError: No module named django_auth_ldap.config beacause pip install django-auth-ldap fails with  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1.

**Comment by arka-nitd** [comment]
I have finished the configuration. Now the server is running. Could you please tell me in details about the app or where's the issue ?

**Comment by hpanago** [comment]
The issue happens when I try to run 'pip install django-auth-ldap'. Not sure if my app is to blame.

Generally: 

It is a simple django blog nothing fancy.
The ldap part, is mostly in views.py in the functions:
def user_exist() where it tries a simple bind to see if it works , def updateuser() where it actually updates the password of the user. Input is taken from django's forms created for this and def register() where it adds a user.

All queries to ldap are done with the admin user with the default pass you see in there. Those queries are os dependent and are to be performed on a Linux(especially for me debian) machine.

**Comment by arka-nitd** [comment]
![image](https://user-images.githubusercontent.com/9302564/31200594-2d4ba0a8-a979-11e7-8623-8fd22d5413e5.png)
Mine installed fine I guess

**Comment by hpanago** [comment]
Glad it works.
For me I had to do these steps http://thefourtheye.in/2013/04/20/installing-python-ldap-in-ubuntu/.
(I am with Debian, I have zero explanation for this).

Anyway, I understand you are here for hacktoberfest and wish to make pull requests. 

The boring task of cleaning up things would go a long way for me. Cleaning all the unnecessary comments that is. But I understand that sounds boring like I said. 
So I would be more that happy to hear, is there anything else you would like to do with this code? 

I could also very easily accept you exporting and adding a totally default ldap database into this repo.

**Comment by arka-nitd** [comment]
I believe screenshot said it all. I haven't contributed to any project yet. Would be a happy to do one. Added a requirements.txt file and corrected few indentation error. Check it that helps :)
